# Docker compose for dev environment

services:
  cloud-db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: cloud-db-password
      POSTGRES_USER: cloud-db-admin
      POSTGRES_DB: cloud-db
    ports:
      - 35432:5432

  cloud-adminer:
    image: adminer
    restart: always
    ports:
      - 38080:8080
